name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag go-web-app:$(date +%s)
    
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN}}
      
    - name: Log in to DigitalOcean Container Registry
      run: doctl registry login

    - name: Tag DigitalOcean Container Registry

    - name: Push image to DigitalOcean Container Registry
      run: docker push registry.digitalocean.com/go-app-artem/go-web-app
